spring:
  application:
    name: mcloud-registry
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3